### ISSUE TITLE
Add support for additional Comparison Operators?

### ISSUE THREAD

**Issue by stewstryker** [APEXGru/manageFilter#1]
The plug-in only seems to support the EQ operator. My application filters also include:

- GTE
- LTE
- IN

I'm a JS lightweight but I'll see what I can do.

More importantly, **thanks for creating this plug-in**. I was trying to use the techniques you showed in https://roelhartman.blogspot.com/2019/03/filtering-in-apex-interactive-grid.html

Your blog instructions worked great when there was only a single filter page item and table column that provided a value for _addFilter_. But when I have multiple page items/columns to _addFilter_ , it wouldn't delete the previous filter on that IG column (even though it said it had deleted it).

**Comment by stewstryker** [comment]
It was simple to add the additional operators I need for my application. Thanks for making the plug-in so extensible.

You can compare your latest version against my fork: https://github.com/stewstryker/manageFilter

**Question for you:**
Your readme.md says:

> The value to filter on should be stored in a Page Item on Page 0

If the IG and the page items are on the same page, is this needed?  If so, I couldn't determine the purpose and it worked fine for me. I haven't worked much with Page 0. What am I missing here?

**Comment by APEXGru** [comment]
I have updated the readme. It is not necessary to have these items on Page 0 - only if you want to use the same / similar feature on a lot of pages it could make sense to define these items on Page 0 (a.k.a. the "Global Page"). 
(Everything you define on Page 0 will render on each and every page of your application.)

**Comment by stewstryker** [comment]
@APEXGru Thanks very much for clarifying that for me. 

My dozen page items are in a different region on the same page as the IG. I hadn't considered having the filters page items used across multiple pages. But that makes sense for some application designs.

I'd tried to implement this myself (without a plug-in) by following the steps in your blog post. But if when I had multiple page items, it would generate multiple IG filters. But your plug-in didn't suffer that flaw. I was also pleased that it works in Apex 19.2 (our current version).

I hope you find my enhancement of the additional operators useful.

Thanks again,

Stew

**Comment by APEXGru** [comment]
Like it a lot!
You can create a pull request (if you want). See https://quayzar.com/git/updating-a-fork-to-the-master-branch-on-github/ for the how-to.
